CREATE DATABASE IF NOT EXISTS estoque_rolos 
  CHARACTER SET utf8mb4 
  COLLATE utf8mb4_unicode_ci;

USE estoque_rolos;

CREATE TABLE IF NOT EXISTS rolos (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  Descrição VARCHAR(50) NOT NULL,
  Milimetragem INT NOT NULL,
  MOQ DECIMAL(10, 3) NOT NULL,
  Estoque DECIMAL(10, 3) NOT NULL,
  MetragemWIP DECIMAL(10, 3) NOT NULL
);
